<?php

if ( ! defined( 'ABSPATH' ) ) {
 exit; // Exit if accessed directly.
}

use SPUI\Controller\ApiKeyController;
use SPUI\Controller\QuotaController;
use SPUI\Model\AiDataModel;

$spui_icon_url  = plugins_url( '/res/images/icon/', SPUI_PLUGIN_FILE );
$spui_robo_icon = $spui_icon_url . '/shortpixel.svg';
$spui_ai_icon   = $spui_icon_url . '/ai.svg';

$spui_item_id  = $this->data['item_id'];
$spui_has_data = $this->data['has_data'];
//$isSupported = $this->data['isSupported'];
$spui_is_different = $this->data['isDifferent'];
$spui_data_items   = implode( ', ', $this->data['dataItems'] );

$spui_is_processable     = $this->data['is_processable'];
$spui_processable_reason = $this->data['processable_reason'];
$spui_processable_status = $this->data['processable_status'];

$spui_quota_controller = QuotaController::getInstance();
$spui_key_controller   = ApiKeyController::getInstance();


if (true === apply_filters('spui/settings/no_ai', false)):

	?>
	<p class='hidden' id='shortpixel-noai'></p>
<?php
endif;

if ( false === $spui_is_processable && $spui_processable_status !== AiDataModel::P_ALREADYDONE ) :

	if ( true === in_array( $spui_processable_status, [ AiDataModel::P_NOJOB ], true ) ) // Silent fail if all done
	{

	}
	else
	{
			printf( '<p>%s</p>', esc_html( $spui_processable_reason ) );
	}
	

elseif ( false === $spui_has_data ) : 

	if ( false === $spui_key_controller->keyIsVerified() && false === $spui_has_data ) :
	
	  		echo wp_kses_post( __( 'Invalid API Key. <a href="options-general.php?page=shortpixel-upscale-settings">Check your Settings</a>', 'shortpixel-upscale-image' ) );

	elseif ( false === $spui_quota_controller->hasQuota() && false === $spui_has_data ) :
	?>
		<p><?php esc_html_e('ShortPixel quota exhausted, the AI SEO data cannot be generated.', 'shortpixel-upscale-image'); ?></p>

	<?php else: ?>

	        <a class='button button-secondary' title="Generate image SEO data with ShortPixel AI (Beta)" href="javascript:window.SPUIProcessor.screen.RequestAlt(<?php echo esc_attr( $spui_item_id ); ?>)">
				<img class="shortpixel-ai-icon ai" src="<?php echo esc_url( $spui_ai_icon ); ?>">	
				<span><?php
				/* translators: %s: Comma-separated list of generated AI data fields. */
				printf( esc_html__( 'AI Image SEO by ShortPixel %s', 'shortpixel-upscale-image' ), esc_html( $spui_data_items ) );
				?></span>
				<img class="shortpixel-ai-icon shortpixel" src="<?php echo esc_url( $spui_robo_icon ); ?>">
			</a>
	        <div class="shortpixel-alt-messagebox" id="shortpixel-ai-messagebox-<?php echo esc_attr( $spui_item_id ); ?>">&nbsp;</div>
	<?php endif; ?>   
<?php else : 
	
	$spui_line_break  = '%0D%0A';
	$spui_mailto_link = 'mailto:support@shortpixel.com?Subject=Wrong AI SEO data generated by ShortPixel AI&Body=ImageURL:  ' . $this->data['image_url'] . "$spui_line_break $spui_line_break Caption:  " . $this->data['result_alt'];
?>

		<p><img class="shortpixel-ai-caption shortpixel-ai-icon shortpixel" src="<?php echo esc_url( $spui_robo_icon ); ?>"> <?php
			/* translators: %s: Comma-separated list of generated AI data fields wrapped in strong tags. */
			$spui_generated_text = __( 'The following image SEO data was generated by ShortPixel AI: %s', 'shortpixel-upscale-image' );
		printf(
			wp_kses_post( $spui_generated_text ),
			'<strong>' . esc_html( $spui_data_items ) . '</strong>'
		);
		?></p>
		
		<a class='button button-secondary' title="<?php esc_attr_e('Restores the previous image SEO data, if available.', 'shortpixel-upscale-image'); ?>" href="javascript:window.SPUIProcessor.screen.UndoAlt(<?php echo esc_attr( $spui_item_id ); ?>, 'undo')"><?php esc_html_e('Undo', 'shortpixel-upscale-image'); ?></a>

	<?php if ( true === $spui_is_different ) : ?>

		<a class='button button-secondary' title="<?php esc_attr_e('Redo', 'shortpixel-upscale-image'); ?>" href="javascript:window.SPUIProcessor.screen.UndoAlt(<?php echo esc_attr( $spui_item_id ); ?>, 'redo')"><?php esc_html_e('Redo', 'shortpixel-upscale-image'); ?></a>
	<?php endif; ?>

		<a class='button button-secondary' title="<?php esc_attr_e('Report to us, via e-mail, an incorrect image SEO data for this image', 'shortpixel-upscale-image'); ?>." href="<?php echo esc_url( $spui_mailto_link ); ?>"><?php esc_html_e('Report', 'shortpixel-upscale-image'); ?></a>

		<a class='button button-secondary' title="<?php esc_attr_e('Send us feedback about this feature, suggest other features, or vote on existing feature requests', 'shortpixel-upscale-image'); ?> ." target="_blank" href="https://ideas.shortpixel.com/"><?php esc_html_e('Feedback', 'shortpixel-upscale-image'); ?></a>

	<?php if ( true === $spui_is_different )
	{
				 /* translators: 1: Opening paragraph tag. 2: Closing paragraph tag. */
			 $spui_changed_text = __( '%1$s The plugin has detected some fields were changed after generating AI Data. You can use the redo button to regenerate AI Data %2$s ', 'shortpixel-upscale-image' );
			 printf(
			 	wp_kses_post( $spui_changed_text ),
			 	'<p>',
			 	'</p>'
			 );
		} ?>

<?php endif; ?>
